In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
ds = pd.read_csv('data/calories.csv')

In [7]:
ds.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0

In [9]:
ds = ds.drop(['User_ID', 'Calories'], axis=1)
ds.head()

   Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0    male   68   190.0    94.0      29.0       105.0       40.8
1  female   20   166.0    60.0      14.0        94.0       40.3
2    male   69   179.0    79.0       5.0        88.0       38.7
3  female   34   179.0    71.0      13.0       100.0       40.5
4  female   27   154.0    58.0      10.0        81.0       39.8

In [10]:
gender_map = {
  'male': 0,
  'female': 1,
}

In [11]:
ds['Gender'] = ds['Gender'].map(gender_map)

In [12]:
ds.head()

   Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0       0   68   190.0    94.0      29.0       105.0       40.8
1       1   20   166.0    60.0      14.0        94.0       40.3
2       0   69   179.0    79.0       5.0        88.0       38.7
3       1   34   179.0    71.0      13.0       100.0       40.5
4       1   27   154.0    58.0      10.0        81.0       39.8

In [13]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      15000 non-null  int64
 1   Age         15000 non-null  int64
 2   Height      15000 non-null  float64
 3   Weight      15000 non-null  float64
 4   Duration    15000 non-null  float64
 5   Heart_Rate  15000 non-null  float64
 6   Body_Temp   15000 non-null  float64
dtypes: float64(5), int64(2)
memory usage: 820.4 KB

In [15]:
from sklearn.mixture import GaussianMixture

model = GaussianMixture()
y_pred = model.fit_predict(ds)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)