In [1]:
import pandas as pd

In [16]:
data = {
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "salary": [3000, 4000, 5000, 6000, 4000, 7000, 5000, 8000, 9000, 10000]
}

In [17]:
ds = pd.DataFrame(data)
ds.sample(4)

   id  salary
9  10   10000
6   7    5000
8   9    9000
7   8    8000

In [ ]:
N = 2

ds_clean = ds.sort_values("salary").drop_duplicates("salary")
res_format = lambda res: pd.DataFrame({"SecondHighestSalary": [res]})

if ds_clean.shape[0] <= 0:
    res_format(None)
else:
    res_format(ds_clean.iloc[N - 1])

id           3
salary    5000
Name: 2, dtype: int64

## ---

In [67]:
department_data = {
    "id": [1, 2, 3],
    "name": ["Engineering", "HR", "Marketing"]
}
employee_data = {
    "id": [101, 102, 103, 104, 105, 106, 107],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "salary": [9000, 6000, 8000, 7500, 6200, 8800, 9000],
    "departmentId": [1, 2, 1, 3, 2, 1, 3]
}

In [69]:
d_ds = pd.DataFrame(department_data)
d_ds

   id         name
0   1  Engineering
1   2           HR
2   3    Marketing

In [70]:
e_ds = pd.DataFrame(employee_data)
e_ds

    id     name  salary  departmentId
0  101    Alice    9000             1
1  102      Bob    6000             2
2  103  Charlie    8000             1
3  104    David    7500             3
4  105      Eva    6200             2
5  106    Frank    8800             1
6  107    Grace    9000             3

In [92]:
e_ds.merge(d_ds, left_on="departmentId", right_on="id").groupby("name_y").apply(
    lambda x: x[x["salary"] == x["salary"].max()]
).reset_index(drop=True)[["name_y", "name_x", "salary"]].rename({
    "name_y": "Department", "name_x": "Employee", "salary": "Salary"
}, axis=1)

    Department Employee  Salary
0  Engineering    Alice    9000
1           HR      Eva    6200
2    Marketing    Grace    9000